server:
  port: 8082

spring:
  application:
    name: activity-service
  mongodb:
    uri: mongodb://localhost:27017/activitydb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/