server:
  port: 8083

spring:
  application:
    name: ai-service

  mongodb:
    uri: mongodb://localhost:27017/ai-recommendation-db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: predictafit.activity.exchange
  queue:
    name: predictafit.activity.created.queue
  routing:
    key: activity.created


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}